name: Deploy

on:
  push:
    branches:
      - deploy # Déclenche uniquement sur la branche 'deploy'
  workflow_dispatch: # Permet le déclenchement manuel

# Section env globale
env:
  AZURE_ENV_NAME: "stpademo"
  REGION: "france"
  RESOURCE_GROUP_NAME: "rg-demo-stpaaca-1803-1310"
  
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-dev-cli-apps:latest
    env:
        AZURE_CREDENTIALS: ${{ secrets.AzureSPN }}
        AZURE_ENV_NAME: ${{ env.AZURE_ENV_NAME }}
        AZURE_LOCATION: ${{ env.REGION }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update azd to the latest version
        run: |
          curl -fsSL https://aka.ms/install-azd.sh | bash

      - name: Log in with Azure (Client Credentials)
        run: |
          $info = $Env:AZURE_CREDENTIALS | ConvertFrom-Json -AsHashtable;
          Write-Host "::add-mask::$($info.clientSecret)"

          azd auth login `
            --client-id "$($info.clientId)" `
            --client-secret "$($info.clientSecret)" `
            --tenant-id "$($info.tenantId)"
        shell: pwsh
        env:
          AZURE_CREDENTIALS: ${{ secrets.AzureSPN }}

      - name: Provision Azure Resources
        run: azd provision --no-prompt
        env:
          AZURE_ENV_NAME: ${{ env.AZURE_ENV_NAME }}
          AZURE_LOCATION: ${{ env.REGION }}
          AZURE_RESOURCE_GROUP_NAME: ${{ env.RESOURCE_GROUP_NAME }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy changes to Azure Container Apps
        run: azd deploy --no-prompt
        env:
          AZURE_ENV_NAME: ${{ env.AZURE_ENV_NAME }}
          AZURE_LOCATION: ${{ env.AZURE_LOCATION }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
